name: Release from template

on:
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - '**/yarn.lock'
      - '**/package-lock.json'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changes in template
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            template:
              - 'template/**/package.json'
              - 'template/**/pnpm-lock.yaml'
              - 'template/**/yarn.lock'
              - 'template/**/package-lock.json'

      - name: Skip if no template changes
        if: steps.changes.outputs.template != 'true'
        run: echo "No changes in template/* – skipping release."

      - name: Setup Node
        if: steps.changes.outputs.template == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure git
        if: steps.changes.outputs.template == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install deps
        if: steps.changes.outputs.template == 'true'
        working-directory: template
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            echo "No lockfile found, skipping install."
          fi

      - name: Compute next version from npm/git/pkg (patch) & tag
        if: steps.changes.outputs.template == 'true'
        working-directory: template
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail

          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version || '0.0.0'")
          echo "Package: $PKG_NAME"
          echo "template/package.json version: $PKG_VERSION"

          REGISTRY_VERSION=$(npm view "$PKG_NAME" version 2>/dev/null || echo '0.0.0')
          echo "npm registry version: $REGISTRY_VERSION"

          GIT_TAG=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1 || true)
          GIT_VERSION=${GIT_TAG#v}
          GIT_VERSION=${GIT_VERSION:-0.0.0}
          echo "highest git tag: ${GIT_TAG:-<none>} → $GIT_VERSION"

          BASE=$(node -e "const vs=['$REGISTRY_VERSION','$GIT_VERSION','$PKG_VERSION'];const s=v=>v.split('.').map(Number);vs.sort((a,b)=>{const A=s(a),B=s(b);for(let i=0;i<3;i++){if(A[i]>B[i])return -1;if(A[i]<B[i])return 1}return 0});console.log(vs[0])")
          echo "Base version: $BASE"

          NEXT=$(node -e "const [x,y,z]='$BASE'.split('.').map(Number);console.log([x,y,z+1].join('.'))")
          echo "Next version: $NEXT"

          npm version "$NEXT" --no-git-tag-version
          git add package.json
          git commit -m "chore(release): v${NEXT} [skip ci]" || echo "No changes to commit"
          git tag "v${NEXT}"
          git push --follow-tags

      - name: Publish to npm
        if: steps.changes.outputs.template == 'true'
        working-directory: template
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
